### PR TITLE
[TrickOrTreat] Handle replies when message not found.

### PR DESCRIPTION
**Pull request by ltzmax**
I ran `style line lenth 99` not sure if you use 99 but.
Also i haven't used this `reference` before so in this way i did it is how i understood how to use it.

### CODE REVIEW

**Comment by aikaterna** [comment]
Could you please add this change to two other places in the code as well? Also if you would like to reformat the file, I use 120 line length as a general rule. Sorry for not having that point listed somewhere on the repo.

```
Ignoring exception in on_message_without_command
Traceback (most recent call last):
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 729, in on_message_without_command
    bot_talking = await message.reply(random.choice(walking_messages))
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/message.py", line 1358, in reply
    return await self.channel.send(content, reference=self, **kwargs)
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
```

```
In message_reference: Unknown message
Ignoring exception in on_message_without_command
Traceback (most recent call last):
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 665, in on_message_without_command
    return await message.reply(random.choice(messages))
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/message.py", line 1358, in reply
    return await self.channel.send(content, reference=self, **kwargs)
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
```

**Comment by ltzmax** [comment]
> Could you please add this change to two other places in the code as well? Also if you would like to reformat the file, I use 120 line length as a general rule. Sorry for not having that point listed somewhere on the repo.
> 
> ```
> Ignoring exception in on_message_without_command
> Traceback (most recent call last):
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 729, in on_message_without_command
>     bot_talking = await message.reply(random.choice(walking_messages))
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/message.py", line 1358, in reply
>     return await self.channel.send(content, reference=self, **kwargs)
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/abc.py", line 1065, in send
>     data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/http.py", line 254, in request
>     raise HTTPException(r, data)
> discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
> ```
> 
> ```
> In message_reference: Unknown message
> Ignoring exception in on_message_without_command
> Traceback (most recent call last):
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 665, in on_message_without_command
>     return await message.reply(random.choice(messages))
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/message.py", line 1358, in reply
>     return await self.channel.send(content, reference=self, **kwargs)
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/abc.py", line 1065, in send
>     data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/http.py", line 254, in request
>     raise HTTPException(r, data)
> discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
> ```

Ah i missed those two places. i was sure i had taken all.
Alright, I did it in 120 this time and no worries. 👍

**Comment by aikaterna** [comment]
```
Ignoring exception in on_message_without_command
Traceback (most recent call last):
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 740, in on_message_without_command
    bot_talking = await message.send(
AttributeError: 'Message' object has no attribute 'send'
```
```
Ignoring exception in on_message_without_command
Traceback (most recent call last):
  File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 660, in on_message_without_command
    return await message.send(
AttributeError: 'Message' object has no attribute 'send'
```

**Comment by ltzmax** [comment]
> ```
> Ignoring exception in on_message_without_command
> Traceback (most recent call last):
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 740, in on_message_without_command
>     bot_talking = await message.send(
> AttributeError: 'Message' object has no attribute 'send'
> ```
> 
> ```
> Ignoring exception in on_message_without_command
> Traceback (most recent call last):
>   File "/Users/aikaterna/redenv/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "/Users/aikaterna/Library/Application Support/Red-DiscordBot/data/nya/cogs/CogManager/cogs/trickortreat/trickortreat.py", line 660, in on_message_without_command
>     return await message.send(
> AttributeError: 'Message' object has no attribute 'send'
> ```

should be fixed now hopefully!

**Pull request merged**
