### PR TITLE
[RSS] added support for targeted channels

### PR DESCRIPTION
**Pull request by owocado**
Added an optional channel parameter after feed_name parameter, for consistency.
Optional, because, it will default to current channel where command was executed if channel parameter is not passed, so users don't have to pass channel parameter every time and only when they want to add a RSS feed to a different channel.
This seems to be working fine, as I have tested this on my instance. Please let me know what do you think!

\+ black reformat

### CODE REVIEW

**Comment by aikaterna** [comment]
I didn't really want help with this, but ok. Reformat with Black at 120 instead of 99 first off please.

**Comment by owocado** [comment]
ok did.

**Comment by aikaterna** [comment]
I don't really like how all of these lines are being overwritten blame wise and I didn't run black on my original work. I was hoping I had run black at 120 at some point on this but I guess not. Can you leave the style alone and just apply your changes.

**Comment by aikaterna** [comment]
Or I'll reformat the whole thing myself so I have the line credit for it. Either way.

**Comment by owocado** [comment]
> Can you leave the style alone and just apply your changes.

ok did.

**Pull request merged**
